[package]
name = "csv-async"
version = "0.0.2"
authors = ["gwierzchowski <gwierzchowski@wp.pl>"]
description = "CSV parsing with support for async."
edition = "2018"
keywords = ["csv", "comma", "parser", "delimited", "async"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bstr = "0.2"
csv-core = "0.1"
futures = "0.3"

[dev-dependencies]
async-std = "1.6"
