coverage:
  status:
    project:
      default:
        threshold: 95% # make CI green anyway
    patch:
      default:
        threshold: 95% # make CI green anyway

ignore: # ignore codecoverage on following paths
  - ".github"
