name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        version:
          - 1.45.0
          - stable
          - beta
          - nightly

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  codecov:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Generate coverage file
      run: |
        which cargo-tarpaulin || cargo install cargo-tarpaulin
        cargo tarpaulin --out Xml --exclude-files *tokio*.rs
    - name: Upload to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: cobertura.xml
